spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=Asia/Seoul
    username: root
    password: yo12ngnam

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 715919494858-i2jad0l92g35nlpa0246c5hjieqn17j9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          kakao:
            client-authentication-method: POST
            client-id: c0442085edb60043e02db1d7bbad3189
            client-secret: FRcCL2dM3fwjH20bb8UIe9VJaN519Poh
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
